app:
  version: v0.1
  max_header_bytes: 2
  max_multipart_memory: 100
  websocket_message_size_limit: 1
  jwt_private_key_path: 
  jwt_public_key_path: 
  public_dir: 
  upload_dir: 
  log_dir: 
  log_time_format: 20060102

ext:
  mail_domain_path: ./data/domains.txt
  geo_ip_path: ./data/GeoLite2-City.mmdb
  profanity_filter_path: ./data/badwords.%s.txt

auth:
  google_fb_path: ./data/firebase.json
  google_id:
  google_secret:
  facebook_id: 
  facebook_secret: 

server:
  scheme: http
  host: 192.168.0.102
  port: 3000
  mode: debug
  read_timeout: 60s
  write_timeout: 60s

database:
  dialect: mysql
  user: user
  password: 12345678
  host: 127.0.0.1
  name: db
  loc: UTC
  max_idle: 10
  max_open: 100

redis:
  host: 127.0.0.1:6379
  password:
  max_idle: 30
  max_active: 30
  idle_timeout: 200s